SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using SportsStore.Models;

namespace SportsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo) => repository = repo;

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

@{

}

<div class="card text-black-80 bg-light mb-3" style="max-width: 18rem; min-width: 30vw;">
    <div class="card-header"><h2>@Model.Name</h2></div>
    <div class="card-body">
        <h5 class="card-title">@Model.Description</h5>
        <h3 class="card-text product-price">@Model.Price.ToString("c")</h3>
    </div>
</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!-- Это - файл компоновки, который можно с легкостью встраивать в другие представления -->
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" asp-href-include="~/lib/bootstrap/css/*.min.css"
          asp-href-exclude="~/lib/bootstrap/css/*-reboot*, ~/lib/bootstrap/css/*-grid*"/>
    <link rel="stylesheet" href="~/Layout/Layout.css" />
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#"><h2 class="navbar-brand">SPORTS STORE</h2></a>
    </nav>

    <div class="grid-container">
        <div class="navbar-categories">
            <div class="categories" id="categories">
                @await Component.InvokeAsync("NavigationMenu")
                <!--Асинхронно вызываем компонент NavigationMenuViewComponent из Components/-->
            </div>
        </div>

        <div class="products-body">
            @RenderBody()
        </div>
    </div>
</body>
</html>